# Site settings
title: Test Driven Development Courses
mobile-title: TDD Courses
email: michael@mherman.org
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "fenced_code_blocks", "with_toc_data"]
baseurl: ""
url: "http://testdriven.io"
twitter: "RealPython"
destination: docs
