# Site settings
title: Test Driven Development Courses
mobile-title: TDD Courses
short-title: TestDriven.io
email: michael@mherman.org
markdown: kramdown
highlighter: rouge
kramdown:
  toc_levels: 2..2
baseurl: ""
url: "https://testdriven.io"
twitter: testdrivenio
destination: docs
source: src
exclude: [old]
